=== vladislavzavadski/Epam-Tasks/Cafe(Task 2)/Menu/menu.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.training.by/2016/MENUSchema"
           xmlns:tns="http://www.training.by/2016/MENUSchema"
           elementFormDefault="qualified">
    <xs:element name="menu">
        <xs:complexType>
            <xs:all>
                <xs:element name="breakfast" type="tns:foodType" minOccurs="0"/>
                <xs:element name="hot-appetizers" type="tns:foodType" minOccurs="0"/> 
                <xs:element name="cold-appetizers" type="tns:foodType" minOccurs="0"/>
            </xs:all>
        </xs:complexType>       
    </xs:element>
    
    <xs:complexType name="foodType">
        <xs:sequence>
            <xs:element name="food" type="tns:food" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="price">
        <xs:sequence>
            <xs:element name="portion-type" type="xs:string"/>
            <xs:element name="portion-cost" type="xs:positiveInteger" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="food">
        <xs:sequence>
            <xs:element name="photo" type="xs:anyURI"/>
            <xs:element name="name" type="tns:russianString"/>
            <xs:element name="description" type="tns:russianString"/>
            <xs:element name="portion-size" type="xs:positiveInteger" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="price" type="tns:price" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
    
    <xs:simpleType name="russianString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[а-яА-Я\s0-9\.,\(\):\-]+"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== vladislavzavadski/Epam-Tasks/Cafe(Task 2)/Menu/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<menu xmlns="http://www.training.by/2016/MENUSchema"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.training.by/2016/MENUSchema menu.xsd">
    <breakfast>
        <food id="ID-1">
            <photo>http://vk.com/food.jpg</photo>
            <name>Глазунья</name>
            <description>2 яйца (на выбор: сыр, витчина, помидоры)</description>
            <portion-size>100</portion-size>
            <portion-size>20</portion-size>
            <portion-size>30</portion-size>
            <price>
                <portion-type>1. Первый тип</portion-type>
                <portion-cost>200</portion-cost>
            </price>
            <price>
                <portion-type>2. Второй тип</portion-type>
                <portion-cost>200</portion-cost>
            </price>
        </food>
        <food id="ID-2">
            <photo>http://vk.com/food.jpg</photo>
            <name>Блинчики с мясом</name>
            <description>Жаренные блинчики с мясом</description>
            <portion-size>100</portion-size>
            <portion-size>20</portion-size>
            <portion-size>30</portion-size>            
            <price>
                <portion-type>kjhkjh</portion-type>
                <portion-cost>200</portion-cost>
            </price>
        </food>        
    </breakfast>
    <cold-appetizers>
        <food id="ID-3">
            <photo>http://vk.com/food.jpg</photo>
            <name>Соленья по-домашнему</name>
            <description>Маринованные овощи</description>
            <portion-size>100</portion-size>
            <portion-size>20</portion-size>
            <portion-size>30</portion-size>            
            <price>
                <portion-type>300</portion-type>
                <portion-cost>200</portion-cost>
            </price>
        </food>
        <food id="ID-4">
            <photo>http://vk.com/food.jpg</photo>
            <name>Мороженое</name>
            <description>Сливочное мороженое</description>
             <portion-size>100</portion-size>
            <portion-size>20</portion-size>
            <portion-size>30</portion-size>            
            <price>
                <portion-type>300</portion-type>
                <portion-cost>200</portion-cost>
            </price>
        </food>        
    </cold-appetizers>   
     
    <hot-appetizers>
        <food id="ID-5">
            <photo>http://vk.com/food.jpg</photo>
            <name>Соленья по-домашнему</name>
            <description>Маринованные овощи</description>
            <portion-size>100</portion-size>
            <portion-size>20</portion-size>
            <portion-size>30</portion-size>       
            <price>
                <portion-type>300</portion-type>
                <portion-cost>200</portion-cost>
            </price>
        </food>
        <food id="ID-6">
            <photo>http://vk.com/food.jpg</photo>
            <name>Мороженое</name>
            <description>Сливочное мороженое</description>
            <portion-size>100</portion-size>
            <portion-size>20</portion-size>
            <portion-size>30</portion-size>     
            <price>
                <portion-type>300</portion-type>
                <portion-cost>200</portion-cost>
            </price>
        </food>        
    </hot-appetizers>     

</menu>
