=== vladislavzavadski/Epam-Tasks/Catalog/resourse/News.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://www.training.by/2016/CatalogSchema"
           xmlns:tns="http://www.training.by/2016/CatalogSchema">

    <xs:element name="catalog">
        <xs:complexType>
            <xs:sequence> 
                <xs:element name = "category" type="tns:categoryType" minOccurs="0" maxOccurs="3">
                    <xs:unique name="unique-subcategory">
                        <xs:selector xpath="tns:subcategory"/>
                        <xs:field xpath="@name"/>    
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="unique-category">
            <xs:selector xpath="tns:category"/>
            <xs:field xpath="@name"/>
        </xs:unique>

    </xs:element>
    
    
    <xs:complexType name="categoryType">
        <xs:sequence>
            <xs:element name="subcategory" type="tns:subcategoryType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="tns:categoryNameType"/>
    </xs:complexType>
    
    <xs:complexType name="subcategoryType">
        <xs:sequence>
            <xs:element name="news" minOccurs="0" maxOccurs="unbounded" type="tns:newsType"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    
    <xs:complexType name="newsType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="author" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="issue-date" type="xs:date" minOccurs="1" maxOccurs="1"/>
            <xs:element name="body" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="categoryNameType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="film"/>
            <xs:enumeration value="disk"/>
            <xs:enumeration value="book"/>
        </xs:restriction>
    </xs:simpleType>    
    
</xs:schema>

=== vladislavzavadski/Epam-Tasks/Catalog/resourse/News.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<catalog xmlns="http://www.training.by/2016/CatalogSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.training.by/2016/CatalogSchema News.xsd">
    <category name="film">
        <subcategory name="poem">
            <news>
                <name>Bla-bla-bla</name>
                <author>qwe</author>
                <author>qwe1</author>
                <author>qwe2</author>
                <issue-date>2016-05-30</issue-date>
                <body>Body</body>
            </news>
            <news>
                <name>Bla-bla-bla</name>
                <author>qwe</author>
                <author>qwe1</author>
                <author>qwe2</author>
                <issue-date>2016-05-30</issue-date>
                <body>Body</body>
            </news>
            <news>
                <name>Bla-bla-bla</name>
                <author>qwe</author>
                <author>qwe1</author>
                <author>qwe2</author>
                <issue-date>2016-05-30</issue-date>
                <body>Body</body>
            </news>
            <news>
                <name>Bla-bla-bla</name>
                <author>qwe</author>
                <author>qwe1</author>
                <author>qwe2</author>
                <issue-date>2016-05-30</issue-date>
                <body>Body</body>
            </news>
        </subcategory>
    </category>
    <category name="disk">
        <subcategory name="music">
            <news>
                <name>Выпьем за любовь</name>
                <author>Vladislav</author>
                <author>Zavadski</author>
                <author>qweeqw</author>
                <issue-date>2016-05-30</issue-date>
                <body>Выпьем за любовьь</body>
            </news>
            <news>
                <name>Выпьем за любовь</name>
                <author>Vladislav</author>
                <author>Zavadski</author>
                <author>qweeqw</author>
                <issue-date>2016-05-30</issue-date>
                <body>Выпьем за любовьь</body>
            </news>
            <news>
                <name>Выпьем за любовь</name>
                <author>Vladislav</author>
                <author>Zavadski</author>
                <author>qweeqw</author>
                <issue-date>2016-05-30</issue-date>
                <body>Выпьем за любовьь</body>
            </news>
            <news>
                <name>Выпьем за любовь</name>
                <author>Vladislav</author>
                <author>Zavadski</author>
                <author>qweeqw</author>
                <issue-date>2016-05-30</issue-date>
                <body>Выпьем за любовьь</body>
            </news>
        </subcategory>
    </category>
</catalog>
